fix: fail pr if not synched

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -15,20 +15,15 @@ jobs:
     if: ${{ github.repository != 'GiGInnovationLabs/endeavour-dotnet-template' }}
     steps:
       - uses: actions/checkout@v2
-        # with:
-        #   fetch-depth: 0
-        #   token: ${{ secrets.GHCR_TOKEN }}
-        #   ref: ${{ github.head_ref }}
-      # - name: Dump GitHub context
-      #   env:
-      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
-      #   run: |
-      #     git branch -vv
-      #     echo "$GITHUB_CONTEXT"
-      # - uses: bahmutov/npm-install@v1.7.7
-      # - run: |
-      #     git reset --hard ${{ github.head_ref }}
-      #     npx semantic-release --debug --no-ci -p semantic-release-commitlint -p @semantic-release/commit-analyzer -b pull/25
+        with:
+          token: ${{ secrets.GHCR_TOKEN }}
+      - run: |
+          make synctpl
+          if [ -n "$(git status --porcelain)" ]; then
+            [ -n "$(git status --porcelain -- Makefile)" ] && make synctpl
+            echo "::error title=synctpl::Microservice is not up to date with endeavour-dotnet-template, use make synctpl to fix."
+            exit 1
+          fi
       - uses: volesen/setup-skaffold@v1.1
         with:
           version: 'v1.33.0'
@@ -36,8 +31,4 @@ jobs:
           docker run -p 5000:5000 -d registry:2
           sleep 8
           skaffold config set -g default-repo "localhost:5000"
-      - run: make test
-        env:
-          GHCR_USER: innovationlabsmt
-          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
-      - run: make build
+      - run: make test build
